server:
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/test}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: ''
    password: ''
app:
  security:
    api-key: 123456-secret-key
  tokenization:
    reject-probability: 0.10
  payment:
    success-probability: 0.7
    max-retries: 3
  product:
    min-stock-display: 1
management:
  endpoints:
    web:
      exposure:
        include: health # Expone solo el endpoint de salud
  endpoint:
    health:
      show-details: always # Muestra los detalles de los health indicators

